latina-in-tech/latina-in-tech.github.io

- .gitignore
- .prettierrc.json
- CODEOWNERS
- package-lock.json
- package.json
This PR adds `prettier` in order to share a common code formatting style across the project.
It also adds `./idea` in `.gitignore` since I use Jetbrains product as IDE 👯
> chore: Add prettier

- src/pages/index.tsx
This PR should fix an error about SSR
see https://nextjs.org/docs/messages/react-hydration-error
> fix: Unhandled Runtime Error

- src/components/Sponsors.tsx
| before | after |
|--------|--------|
| ![Screenshot 2023-11-06 alle 08 23 27](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/095bda3c-3dc0-45ac-acae-ab741d6ea3dc) | ![Screenshot 2023-11-06 alle 08 21 04](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/50fb11ab-05ef-41f8-b19d-19c9ed32e228) |
> feat: Improve `Sponsors` ui

- _events/20231129.mdx
- src/components/EventWidget.tsx
- src/model/event.ts
- src/pages/index.tsx
This PR adds the ability to specify the event duration in minutes
If it's not specified, the default is 120 minutes
> Feat: Support event duration

- .github/workflows/verify-code.yml
- package.json
Adds new workflow to verify PR code.
Scripts added:
-  prettier:check: "prettier --check \"src/**/*.(ts|tsx)\""
- check:types: "tsc --noemit"
> feat: adds PR code check workflow

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- code-of-conduct.md
- Adds contribuiting guideline
- Adds issue templates
- Adds PR template
We want to open our code to community contributors, so we have to add as much informations we have and add code rules to the repo
> Open code to contributors

- .vscode/settings.json
- src/pages/feedback/new.tsx
- src/service/feedback/save.ts
- src/service/firebaseConfig.ts
- Adds env variables
- Uses firebase's signInAnonymously
> fix: adds singInAnonym & adds env vars

- .github/workflows/build-and-deploy.yml
> Fix build env 3

- _events/20231129.mdx
Adds November 29th event's [Youtube URL](https://www.youtube.com/watch?v=81DfVfQNycI)
> feat: adds november event's youtube url

- src/components/Newsletter.tsx
- src/components/Sponsors.tsx
- src/pages/index.tsx
This PR closes Discussion #30 
- Adds newsletter section with integration with [Mailchimp](https://mailchimp.com/it), they have a [free plan](https://mailchimp.com/it/pricing) that includes 1K email sent per month
- With Mailchimp we can build custom HTML template (brand logo is mandatory) to embed in our website
- With Mailchimp we [can integrate easily with eventbrite](https://www.eventbrite.it/apps/mailchimp/), to include in the email campaigns users who register for our events
We want to have a direct endpoint with our users.
- clone this branch 
- start the app
- try to insert invalid email in the newsletter section
- you should not be able to register to newsletter
- try to insert a valid email
- press enter or press the button
- you should be redirected to captha page
- solve …
> feat: Adds newsletter

- _events/20231221.mdx
This PR fixes the event's scheduled time
| before | after |
|--------|--------|
| ![before](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/4373daa9-ddaf-4aba-aa9b-59d4746fb366) | ![after](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/695bdd1e-c892-4117-b628-03c6bfcec040)|
> fix: Event time should be from 19.15 to 20.30

- src/components/Newsletter.tsx
- src/pages/newsletter/index.tsx
This PR allows to reach the newsletter with a dedicated URL
We need to target this content with a dedicated URL to give users a fast and easy UX 
http://localhost:3000/newsletter
| desktop | mobile |
|--------|--------|
| ![Screenshot 2023-12-18 alle 09 27 58](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/35b4cf0d-7ed9-4e4f-b98e-c35f7d88ea7d) | ![Screenshot 2023-12-18 alle 09 27 39](https://github.com/latina-in-tech/latina-in-tech.github.io/assets/822471/84238213-d2c5-40a9-b135-acd87e00342c) | 
PS: @coluzziandrea I changed a bit the wording of the newsletter slogan (feat ChatGPT 🤖 ). Feel free to reject it if you find it low-fitting
> feat: Newsletter as a dedicate page

- README.md
Minor changes to update the README with the new web site url
> chore: Update README.md with the new web site url

- _events/20230404.mdx
- _events/20230509.mdx
- _events/20230606.mdx
- _events/20230629.mdx
- _events/20230922.mdx
- src/components/event/EventActions.tsx
- src/components/event/EventSlides.tsx
- src/model/event.ts
- src/pages/events/[slug].tsx
- src/pages/index.tsx
Adds slides to event page
We want to improve the event page.
> Followup event page

- _events/20231221.mdx
Added december slides from Massimo Bonanni
> feat: Added december slides

- _events/20240116.mdx
Adds youtube URL for Jan 2024 event
> feat: Adds youtube URL for Jan 2024 event

- .github/workflows/stale.yml
By removing this parameter, it should be fixed
> fix: Stale actions doesn't close PRs in stale from 7 days

- docs/community/README.md
All links point to 404 not-found pages
> fix: fix `docs/community/README.md`broken links

- _community/members/aionta.mdx
- src/pages/community/index.tsx
It also fixes an issue about server hydration
> fix: Community member's bio exceeds max length

- _events/20240403.mdx
> fix: Speaker name typo

- src/pages/[lang]/feedback/new.tsx
> fix: eslint error

- _events/20240918.mdx
> fix: 20240918 | coding gym vol III

- _events/20241029.mdx
> fix: 20241029 | coding gym vol IV

- dictionaries/en.json
- dictionaries/it.json
- src/components/Hero.tsx
- src/components/LeaveFeedback.tsx
- src/components/Newsletter.tsx
- src/components/event/EventWidget.tsx
- src/pages/[lang]/admins/team.tsx
- src/pages/[lang]/community/index.tsx
- src/pages/[lang]/events/index.tsx
- src/pages/[lang]/feedback/new.tsx
- src/pages/[lang]/index.tsx
- src/pages/[lang]/newsletter/index.tsx
- src/utils/dictionary.ts
- Adds missing translations for english language
While english is selected we can still see many italian tokens
- Translate also events content
> feat: adds translations

- package-lock.json
- package.json
This reverts commit 88bb327e952fbb28d2992c7e0f6d6b59f97a4c55.
> Revert "chore(deps): bump tailwindcss from 3.4.7 to 4.0.0 (#364)"
